version: "3.8"

services:
  parent-auth-db:
    image: postgres:15
    container_name: parent-auth-db
    environment:
      POSTGRES_DB: parent_auth_db
      POSTGRES_USER: parent_auth_user
      POSTGRES_PASSWORD: parent_auth_pass
    ports:
      - "5432:5432"
    volumes:
      - parent_auth_pgdata:/var/lib/postgresql/data

volumes:
  parent_auth_pgdata:
