apiVersion: v1
kind: ConfigMap
metadata:
  name: rds-config

data:
  DATABASE_URL: "school-management-system-db-cluster.cluster-c6v2ekk64hb4.us-east-1.rds.amazonaws.com"
  DATABASE_NAME: "postgres"
  DATABASE_PORT: "5432" 
