apiVersion: v1
kind: ConfigMap
metadata:
  name: rds-config
data:
  DB_HOST: "school-management-system-db-cluster.cluster-c6v2ekk64hb4.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "parent_auth_db"