apiVersion: apps/v1
kind: Deployment
metadata:
  name: parent-auth-service
  labels:
    app: parent-auth-service

spec:
  replicas: 3
  selector:
    matchLabels:
      app: parent-auth-service
      
  template:
    metadata:
      labels:
        app: parent-auth-service
    spec:
      containers:
        - name: parent-auth-service
          image: 566855233164.dkr.ecr.us-east-1.amazonaws.com/parent-auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

          # startupProbe:
          #   httpGet:
          #     path: /health/startup
          #     port: 8081
          #   periodSeconds: 10
          #   failureThreshold: 30
          #   timeoutSeconds: 2

          # readinessProbe:
          #   httpGet:
          #     path: /health/ready
          #     port: 8081
          #   periodSeconds: 10
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
          #   failureThreshold: 3

          # livenessProbe:
          #   httpGet:
          #     path: /health/live
          #     port: 8081
          #   periodSeconds: 15
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 2
          #   failureThreshold: 3

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
