apiVersion: apps/v1
kind: Deployment
metadata:
  name: parent-auth-service
  labels:
    app: parent-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parent-auth-service
  template:
    metadata:
      labels:
        app: parent-auth-service
    spec:
      containers:
        - name: parent-auth-service
          image: 566855233164.dkr.ecr.us-east-1.amazonaws.com/parent-auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: rds-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: SPRING_DATASOURCE_PASSWORD

            - name: SERVER_PORT
              value: "8081"

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          