apiVersion: v1
kind: Service
metadata:
  name: parent-auth-service
spec:
  selector:
    app: parent-auth-service
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8080 
  type: ClusterIP


